# Example secret. In real ops we'd use SealedSecrets, External Secrets Operator, or AWS Secrets Manager.
apiVersion: v1
kind: Secret
metadata:
  name: saathigo-secrets
  namespace: saathigo
type: Opaque
stringData:
  jwt_secret: "REPLACE-WITH-32+CHAR-RANDOM"
  redis_url: "redis://saathigo-redis-cluster.saathigo.svc.cluster.local:6379"
  database_url: "postgres://saathigo:CHANGE_ME@saathigo-postgres.saathigo.svc.cluster.local:5432/saathigo"
